import { SchemaBuilder } from "../framework/SchemaBuilder.js";
import { registerNewCollection,addNewCustomManagedBysystem } from "../utils/registerSchema.js";
import { dbAppIns } from "../dpApp.js";


export function defineAccountAndPublicInfoSchema() {
    const builder = new SchemaBuilder("users");

    builder
        // Top-Level Identifier
        .string({
            name: "username",
            attrs: { minLength: 3, maxLength: 30 },
            config: { required: true, immutable: true }
        })

        // =========================================================================
        // ACCOUNT INFO (Authentication, Security, Roles, System Metadata)
        // =========================================================================
        .object({
            name: "accountInfo",
            attrs: { description: "Core account credentials and access metadata" },
            config: { required: true }
        })
        .string({
            name: "accountInfo.email",
            attrs: { pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$" },
            config: { required: true }
        }).
        string({
            name: "accountInfo.password",
            attrs: { description: "password " },
            config: { required: true, select: false } // Omitted from default queries
        })
        .string({
            name: "accountInfo.passwordHash",
            attrs: { description: "Bcrypt or Argon2 password hash" },
            config: { required: true, select: false } // Omitted from default queries
        })
        .string({
            name: "accountInfo.salt",
            attrs: { description: "Cryptographic salt value" },
            config: { 
                required: false, 
                select: false, 
                 // Auto-generated by system
            }
        })
        .number({
            name: "accountInfo.roleId",
            attrs: { type: "int", minimum: 1 },
            config: { 
                required: true, 
                restrictedRoles: ["ADMIN"] // Binary engine index; mutation requires ADMIN
            }
        }).
        number({
            name: "accountInfo.age",
            attrs:{ type: "int" , minimum: 18 },
            config:{ required:true }

        })
        .string({
            name: "accountInfo.roleName",
            attrs: { minLength: 2, maxLength: 50 },
            config: { 
                required: true, 
                restrictedRoles: ["ADMIN"] // Human-readable role string
            }
        })
        .string({
            name: "accountInfo.userType",
            attrs: { enum: ["MEMBER", "BUYER", "SELLER", "COMPANY"] },
            config: { required: true }
        })
        .string({
            name: "accountInfo.status",
            attrs: { enum: ["PENDING", "ACTIVE", "SUSPENDED"] },
            config: { 
                required: true, 
                restrictedRoles: ["ADMIN"] // Operational state managed by admin
            }
        })

        // =========================================================================
        // PUBLIC INFO (Profile Information Accessible to External Users)
        // =========================================================================
        .object({
            name: "publicInfo",
            attrs: { description: "Publicly accessible profile information" },
            config: { required: true }
        })
        .string({
            name: "publicInfo.firstName",
            attrs: { minLength: 2, maxLength: 50, pattern: "^[a-zA-Z\\s'-]+$" },
            config: { required: true }
        })
        .string({
            name: "publicInfo.middleName",
            attrs: { maxLength: 50, pattern: "^[a-zA-Z\\s'-]+$" },
            config: { required: false } // Optional field
        })
        .string({
            name: "publicInfo.lastName",
            attrs: { minLength: 2, maxLength: 50, pattern: "^[a-zA-Z\\s'-]+$" },
            config: { required: true }
        })
        .string({
            name: "publicInfo.displayName",
            attrs: { minLength: 2, maxLength: 150 },
            config: { 
                required: false, 
                managedBySystem: { type: "formatDisplayName" } // Generated from name components
            }
        })
        .string({
            name: "publicInfo.bio",
            attrs: { maxLength: 500 },
            config: { required: false }
        })
        .string({
            name: "publicInfo.city",
            attrs: { maxLength: 100 },
            config: { required: false }
        })
        .string({
            name: "publicInfo.avatarUrl",
            attrs: { description: "CDN URL to avatar image asset" },
            config: { required: false }
        })
        .string({
            name: "publicInfo.headerPhotoUrl",
            attrs: { description: "CDN URL to banner photo asset" },
            config: { required: false }
        }).index({"accountInfo.email":1},{unique:true})

        .withTimestamps()
        .withVersionConcurrencyControl();

       
    return builder;
}
/*register your schemabuidler instance class */
dbAppIns.registerSchema("users",defineAccountAndPublicInfoSchema());
//registerNewCollection("users",defineAccountAndPublicInfoSchema());

function mergeNames(doc) {
  if (!doc) return "";

  // 1. Resolve where the data lives (nested publicInfo OR root level)
  const source = doc.publicInfo || doc;

  // 2. Extract values with fallbacks for naming variations
  const firstName = source.firstName || source.first_name || "";
  const middleName = source.middleName || source.middle_name || source.secondName || source.second_name || "";
  const lastName = source.lastName || source.last_name || "";

  // 3. Filter out empty strings/nulls and join with a single space
  return [firstName, middleName, lastName]
    .map(name => (typeof name === "string" ? name.trim() : ""))
    .filter(Boolean) // Removes empty strings ("") or null/undefined
    .join(" ");
}

/** register you custom managed by system  */
dbAppIns.registerCustomManagedBySystem("formatDisplayName",mergeNames)
//addNewCustomManagedBysystem( "formatDisplayName",mergeNames)



